export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: 'Engineering' | 'Industry News' | 'Compliance';
  publishedAt: string;
  readTime: string;
  imageUrl: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'minimizing-leakage-inductance-smps',
    title: 'Minimizing Leakage Inductance in SMPS Transformers',
    category: 'Engineering',
    publishedAt: 'May 18, 2026',
    readTime: '6 min read',
    excerpt: 'Learn about the causes of leakage inductance in Switching Mode Power Supplies and explore practical winding techniques to minimize it.',
    imageUrl: '/images/blog_transformer_design.png',
    content: `
# Minimizing Leakage Inductance in SMPS Transformers

In switch-mode power supplies (SMPS), the performance of the high-frequency switching transformer plays a critical role in determining overall system efficiency. One of the most common issues engineers face during design is **leakage inductance**.

Leakage inductance occurs when some of the magnetic flux generated by the primary winding does not link with the secondary winding. This uncoupled energy cannot be transferred to the output, causing voltage spikes, higher thermal stress on the switching MOSFET, and electromagnetic interference (EMI).

## Why Leakage Inductance Occurs
In a perfect transformer, 100% of the magnetic flux flows through the core and couples all windings. However, in reality, winding layout, insulation tape, and core geometry create air gaps through which some flux "leaks."

## Effective Winding Techniques to Reduce Leakage
1. **Primary Winding Sandwiching (Interleaving)**:
   This is the most effective method. Instead of winding the entire primary and then the secondary, you split the primary into two halves (inner and outer) and place the secondary winding in between them. This significantly reduces the physical distance between the primary and secondary coils, improving coupling.
   
2. **Minimize Insulation Thickness**:
   While safety margins (creepage/clearance) must be respected, excessive tape thickness increases spacing and worsens leakage. Using triple-insulated wire (TIW) for the secondary winding can eliminate the need for margin tape, saving space and improving coupling.
   
3. **Use Litz Wire**:
   At high frequencies, the skin effect and proximity effect increase wire resistance. Using Litz wire (many strands of thin insulated wire twisted together) distributes the current more evenly, decreasing DCR and improving flux link.
   
4. **Winding Across Full Bobbin Width**:
   Ensure that the wire occupies the full width of the bobbin window. A narrow winding with large gaps at the ends will have significantly higher leakage inductance than a flat, full-width layer.

## Conclusion
By implementing sandwich windings and optimizing wire selection, design engineers can drop leakage inductance to less than 1% of the primary inductance. At Supreme Systems Solution, our winding designs are customized to achieve these tight tolerances, boosting SMPS efficiency and lowering EMI.
    `
  },
  {
    slug: 'role-common-mode-chokes-emi-suppression',
    title: 'The Role of Common Mode Chokes in EMI Suppression',
    category: 'Compliance',
    publishedAt: 'June 02, 2026',
    readTime: '5 min read',
    excerpt: 'An in-depth guide on how common mode chokes filter out high-frequency noise and help electronic products pass compliance audits.',
    imageUrl: '/images/blog_chokes_filtering.png',
    content: `
# The Role of Common Mode Chokes in EMI Suppression

Electromagnetic Compatibility (EMC) is a major hurdle for any new electronics product. To achieve certifications like CE, FCC, or UL, electronic circuits must limit the noise they inject back into power lines. **Common Mode Chokes** are the front-line defense in filtering out this unwanted electrical noise.

## Understanding Common and Differential Mode Noise
Noise on AC/DC power lines is classified into two types:
* **Differential Mode Noise**: Flows in opposite directions through the supply line and return line.
* **Common Mode Noise**: Flows in the same direction on both power lines and returns via the system ground/earth.

Common mode noise is particularly challenging because it easily radiates from cables, acting like an antenna.

## How a Common Mode Choke Works
A common mode choke consists of two identical windings wound on a single magnetic core (usually high-permeability toroidal ferrite or nanocrystalline). The windings are oriented such that currents flowing in the same direction (common mode) create opposing magnetic fields inside the core, creating high impedance and blocking the noise.

Conversely, currents flowing in opposite directions (the desired power or signal current) create magnetic fields that cancel each other out, passing through the choke with virtually zero impedance.

## Selecting Core Materials: Ferrite vs. Nanocrystalline
* **Manganese-Zinc (MnZn) Ferrite**: Traditional material, offers good impedance up to a few megahertz. Cost-effective.
* **Nanocrystalline**: Provides extremely high permeability (up to 10x that of ferrite). This allows for much smaller chokes with the same inductance, and they maintain performance across a wider temperature range.

## Designing with Chokes
To ensure optimal suppression, place the common mode choke as close to the power input connector as possible. Keep the input and output tracks separated to prevent the noise from bypass-coupling over the choke.

Supreme Systems Solution design engineers specialize in choosing core geometries and winding styles that target the specific noise frequencies of your power supply.
    `
  },
  {
    slug: 'benefits-of-custom-wound-magnetics',
    title: 'Why Standard Off-the-Shelf Coils Might Fail Your Application',
    category: 'Engineering',
    publishedAt: 'June 07, 2026',
    readTime: '4 min read',
    excerpt: 'Discover why specialized industrial equipment, automotive modules, and custom chargers require bespoke custom magnetic solutions.',
    imageUrl: '/images/blog_custom_manufacturing.png',
    content: `
# Why Standard Off-the-Shelf Coils Might Fail Your Application

When building a prototype, it is tempting to browse catalogs and order a standard inductor or transformer. However, as designs shrink, frequency bands increase, and power efficiency requirements tighten, catalog parts often fall short.

## The Limitations of Catalog Magnetics
1. **Compromised Footprints**:
   Off-the-shelf magnetics are made in standard sizes. They might be too tall for low-profile enclosures or too wide, eating up precious PCB real estate.
   
2. **Thermal Overload**:
   Standard components are rated for generic ambient conditions. If your device is sealed inside a hot enclosure or used in automotive compartments, a catalog coil can saturate quickly and fail.
   
3. **Inefficient Core Tuning**:
   Catalog inductors are designed to satisfy broad markets. A custom inductor can use specialized core mixes (like Sendust or High Flux) configured specifically for your circuit's ripple current, leading to smaller sizes and higher efficiency.
   
4. **Poor EMI Profile**:
   Standard components rarely match your system's exact EMI profile. A custom shielded choke or transformer can be wound to direct electromagnetic flux away from sensitive analog pathways on your board.

## The Custom Solution Advantage
At Supreme Systems Solution, custom coil design is our core service. We design components that:
* Fit perfectly within your mechanical constraints.
* Maintain stable inductance under high operating temperatures.
* Utilize advanced winding profiles (such as helical windings or multi-layer interleaved structures).
* Reduce overall BOM cost by combining multiple functions into a single magnetic module.

Contact our design desk to see how custom-wound magnetics can elevate your next generation of power converters.
    `
  }
];
export const categories = ['All', 'Engineering', 'Industry News', 'Compliance'] as const;
